//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Skeldal.rc
//
#define IDS_WINTITLE                    1
#define IDS_CFGGENERAL                  100
#define IDR_BOLDCZ                      101
#define IDS_CFGSOUND                    101
#define IDD_LADICIOKNO                  102
#define IDS_CFGVIDEO                    102
#define IDD_INPUTWINDOW                 103
#define IDS_CFGEXTRAS                   103
#define IDB_INITLOGO                    104
#define IDD_CFGSOUND                    104
#define IDS_CFGCHEATS                   104
#define IDD_CFGTABDIALOG                105
#define IDS_NICVYBRANO                  105
#define IDD_CFGGENERAL                  106
#define IDD_CFGVIDEO                    109
#define IDD_CFGEXTRAS                   111
#define IDD_CFGCHEATS                   112
#define IDB_UVODNIPOZADI                113
#define IDB_UVODNISELECT                114
#define IDD_INSTALL                     115
#define IDI_MAINICON                    117
#define IDD_RTFVIEWER                   122
#define IDR_EXTRAS                      124
#define IDD_SELADV                      128
#define IDB_SELADVDLG                   130
#define IDR_WINAMPPLUGS                 131
#define IDD_DIALOG1                     132
#define IDD_LISTDIALOG                  132
#define IDS_CHEATWARNING1               200
#define IDS_CHEATWARNING2               201
#define IDS_CHEATWARNING3               202
#define IDS_CHEATWARNING4               203
#define IDS_CHEATWARNING5               204
#define IDS_RICHEDMISSING               205
#define IDS_MIXFREQINVALID              206
#define IDS_SCREENBPPWARNING            207
#define IDS_INSTALLFILTER               208
#define IDS_INSTALLTITLE                209
#define IDS_INSTALLPRENAME              210
#define IDS_INSTALLCDFILE               211
#define IDS_INSTALLCDTITLE              212
#define IDS_INSTALLCDFILTER             213
#define IDS_CREATEDIR                   214
#define IDS_NELZEVYTVORITSLOZKU         215
#define IDS_INSTALLEDGAME               216
#define IDS_INSTALLHDD                  217
#define IDS_INSTALLCHYBISOUBOR          218
#define IDS_INSTALLTEXT1                219
#define IDS_INSTALLTEXT2                220
#define IDS_DEFAULTADV                  221
#define IDC_OUTPUT                      1000
#define IDC_ADVENCE                     1001
#define IDC_VALUE                       1002
#define IDC_CLEARMAP                    1003
#define IDC_RAISEDEATH                  1004
#define IDC_GOTO                        1005
#define IDC_PROMPT                      1005
#define IDC_IMMORTAL                    1006
#define IDC_TAB                         1006
#define IDC_RAISEMONSTER                1007
#define IDC_WINDOWED                    1007
#define IDC_LOADITEM                    1008
#define IDC_PRELOAD                     1008
#define IDC_LOADMAP                     1009
#define IDC_AUTOSAVE                    1009
#define IDC_NETECNOST                   1010
#define IDC_OPENDOOR                    1011
#define IDC_GAMESPEED                   1011
#define IDC_PURGE                       1012
#define IDC_GAMESPEEDINFO               1012
#define IDC_REFRESH                     1013
#define IDC_MIXFREQ                     1013
#define IDC_RELOADMOBILES               1014
#define IDC_TAKEMONEY                   1015
#define IDC_UNAFFECT                    1016
#define IDC_SNDMUSIC                    1016
#define IDC_WEAPONSKILL                 1017
#define IDC_SNDFX                       1017
#define IDC_HEAL                        1018
#define IDC_SKIPINTRO                   1019
#define IDC_FULLRESVIDEO                1020
#define IDC_DEBUGCONSOLE                1021
#define IDC_NOHUNGRY                    1022
#define IDC_INSTALLED                   1025
#define IDC_RADIO2                      1028
#define IDC_EDIT2                       1029
#define IDC_BROWSEHDD                   1030
#define IDC_EDIT3                       1031
#define IDC_BROWSEHDD2                  1032
#define IDC_CHECK1                      1033
#define IDC_CREATELINK                  1033
#define IDC_INSTHLAVNI                  1035
#define IDC_INSTALLMUSIC                1036
#define IDC_CLIENTDESK                  1036
#define IDC_INSTALLVIDEO                1037
#define IDC_GAMESPEEDDEFAULT            1037
#define IDC_EXTRASHELP                  1038
#define IDC_RICHEDIT                    1040
#define IDC_CHEATPASSWORD               1041
#define IDC_BATTLEACC                   1042
#define IDC_LIST                        1044
#define IDC_ZOOM1                       1045
#define IDC_ZOOM2                       1046
#define IDC_ZOOM3                       1047
#define IDC_MON1                        1048
#define IDC_MON2                        1049
#define IDC_MON3                        1050
#define IDC_CESTANAPLUGINY              1050
#define IDC_PLUGLIST                    1051
#define IDC_PLUGVLASTNOSTI              1052
#define IDC_PLUGINYNAPOVEDA             1053
#define IDC_HODNOTA                     1054
#define IDC_EXRANDOMBACKFIRES           2000
#define IDC_EXRESPAWNMONSTERS           2001
#define IDC_EXALTERNATEFIGHT            2002
#define IDC_EXRECORVERITEMS             2003
#define IDC_EXBAGEXTENDED               2005
#define IDC_EXSHIELDBLOCKING            2006
#define IDC_EXFASTTRADE                 2007
#define IDC_EXALWAYSMINIMAP             2008
#define IDC_EXGROUPFLEE                 2009
#define IDC_EXAUTOOPENBOOK              2011
#define IDC_EXAUTOSHOWRUNE              2012
#define IDC_EXMOBDIAGONAL               2013

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1055
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
