#define VERSION_MAJOR 1
#define VERSION_MAJORT "1"
#define VERSION_MINOR 2
#define VERSION_MINORT "2"
#define VERSION_BUILD 15
#define VERSION_BUILDT "15"


#define VERSION VERSION_MAJORT"."VERSION_MINORT" Build "VERSION_BUILDT
#define VERSIONNUM VERSION_MAJOR*1000000+VERSION_MINOR*10000+VERSION_BUILD
#define VERSIONWINSTR VERSION_MAJORT","VERSION_MINORT","0","VERSION_BUILDT
#define VERSIONWINRES(x) x VERSION_MAJOR, VERSION_MINOR, 0, VERSION_BUILD

